version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  web:
    image: 'registry.gitlab.com/lappis-unb/services/salic-ml-web/web:homolog'
    command: ["./init_dev.sh"]
    volumes:
      - ./data:/usr/local/lib/python3.6/dist-packages/data
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
      - PYTHONIOENCODING=utf-8
      - SUBPATH=salicml
      - SALIC_DB_HOST=
      - SALIC_DB_PORT=
      - SALIC_DB_USER=
      - SALIC_DB_PASSWORD=

volumes:
  postgres:

