# Generated by Django 2.0.7 on 2018-08-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_auto_20180801_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='name',
            field=models.CharField(default='Metric', max_length=200),
        ),
        migrations.AddField(
            model_name='metric',
            name='reason',
            field=models.CharField(default='Any reason', max_length=500),
        ),
    ]
