# Generated by Django 2.0.7 on 2018-08-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_auto_20180801_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='name',
            field=models.CharField(default='Evidence', max_length=200),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='slug',
            field=models.TextField(max_length=280),
        ),
        migrations.AlterField(
            model_name='metricfeedback',
            name='reason',
            field=models.TextField(max_length=500),
        ),
    ]
