# Generated by Django 2.0.7 on 2018-08-07 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0007_auto_20180807_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='tag',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metric',
            name='tag',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
