# Generated by Django 2.0.7 on 2018-08-07 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0008_auto_20180807_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='tag',
        ),
    ]
