# Generated by Django 2.0.7 on 2018-09-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0009_auto_20180807_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='outlier',
            field=models.FloatField(default=0.0),
        ),
    ]
