# Generated by Django 2.0.7 on 2018-08-29 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0009_auto_20180807_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name_plural': 'Entities'},
        ),
    ]
